services:
  - type: web
    name: inventory-checker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
    autoDeploy: true